# Generated by Django 5.0.6 on 2024-06-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "patient",
            "0002_alter_patient_address_alter_patient_allergy_history_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("X_ray", models.ImageField(blank=True, upload_to="X_ray")),
                ("results", models.JSONField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
