# Generated by Django 5.0.6 on 2024-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_descreption_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="static/avatar/default.jpg", upload_to="static/avatar/"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
