# Generated by Django 5.0.6 on 2024-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_avatar_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(default="avatar/default.jpg", upload_to="avatar/"),
        ),
    ]
