# Generated by Django 5.0.6 on 2024-06-21 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="descreption",
            new_name="description",
        ),
    ]
